export enum LANG_CODE {
  AUTO = "AUTO",
  LANG_EN = "LANG_EN",
  LANG_ZH = "LANG_ZH",
  LANG_ZH_TW = "LANG_ZH_TW",
  LANG_HI = "LANG_HI",
  LANG_ES = "LANG_ES",
  LANG_AR = "LANG_AR",
  LANG_FR = "LANG_FR",
  LANG_BN = "LANG_BN",
  LANG_PT = "LANG_PT",
  LANG_RU = "LANG_RU",
  LANG_UR = "LANG_UR",
  LANG_ID = "LANG_ID",
  LANG_DE = "LANG_DE",
  LANG_JA = "LANG_JA",
  LANG_VI = "LANG_VI",
  LANG_TH = "LANG_TH",
  LANG_KO = "LANG_KO",
}

export const LANG = {
  [LANG_CODE.AUTO]: "Auto",
  [LANG_CODE.LANG_EN]: "English",
  [LANG_CODE.LANG_ZH]: "Chinese(Simplified)",
  [LANG_CODE.LANG_ZH_TW]: "Chinese(Traditional)",
  [LANG_CODE.LANG_HI]: "Hindi",
  [LANG_CODE.LANG_ES]: "Spanish",
  [LANG_CODE.LANG_AR]: "Arabic",
  [LANG_CODE.LANG_FR]: "French",
  [LANG_CODE.LANG_BN]: "Bengali",
  [LANG_CODE.LANG_PT]: "Portuguese",
  [LANG_CODE.LANG_RU]: "Russian",
  [LANG_CODE.LANG_UR]: "Urdu",
  [LANG_CODE.LANG_ID]: "Indonesian",
  [LANG_CODE.LANG_DE]: "German",
  [LANG_CODE.LANG_JA]: "Japanese",
  [LANG_CODE.LANG_VI]: "Vietnamese",
  [LANG_CODE.LANG_TH]: "Thai",
  [LANG_CODE.LANG_KO]: "Korean",
} as const
