/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TranslateImport } from './routes/translate'
import { Route as IndexImport } from './routes/index'
import { Route as ModelManagementIndexImport } from './routes/model-management.index'
import { Route as ModelManagementManageDefaultModelsImport } from './routes/model-management.manage-default-models'

// Create/Update Routes

const TranslateRoute = TranslateImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ModelManagementIndexRoute = ModelManagementIndexImport.update({
  id: '/model-management/',
  path: '/model-management/',
  getParentRoute: () => rootRoute,
} as any)

const ModelManagementManageDefaultModelsRoute =
  ModelManagementManageDefaultModelsImport.update({
    id: '/model-management/manage-default-models',
    path: '/model-management/manage-default-models',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateImport
      parentRoute: typeof rootRoute
    }
    '/model-management/manage-default-models': {
      id: '/model-management/manage-default-models'
      path: '/model-management/manage-default-models'
      fullPath: '/model-management/manage-default-models'
      preLoaderRoute: typeof ModelManagementManageDefaultModelsImport
      parentRoute: typeof rootRoute
    }
    '/model-management/': {
      id: '/model-management/'
      path: '/model-management'
      fullPath: '/model-management'
      preLoaderRoute: typeof ModelManagementIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/translate': typeof TranslateRoute
  '/model-management/manage-default-models': typeof ModelManagementManageDefaultModelsRoute
  '/model-management': typeof ModelManagementIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/translate': typeof TranslateRoute
  '/model-management/manage-default-models': typeof ModelManagementManageDefaultModelsRoute
  '/model-management': typeof ModelManagementIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/translate': typeof TranslateRoute
  '/model-management/manage-default-models': typeof ModelManagementManageDefaultModelsRoute
  '/model-management/': typeof ModelManagementIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/translate'
    | '/model-management/manage-default-models'
    | '/model-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/translate'
    | '/model-management/manage-default-models'
    | '/model-management'
  id:
    | '__root__'
    | '/'
    | '/translate'
    | '/model-management/manage-default-models'
    | '/model-management/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TranslateRoute: typeof TranslateRoute
  ModelManagementManageDefaultModelsRoute: typeof ModelManagementManageDefaultModelsRoute
  ModelManagementIndexRoute: typeof ModelManagementIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TranslateRoute: TranslateRoute,
  ModelManagementManageDefaultModelsRoute:
    ModelManagementManageDefaultModelsRoute,
  ModelManagementIndexRoute: ModelManagementIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/translate",
        "/model-management/manage-default-models",
        "/model-management/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/translate": {
      "filePath": "translate.tsx"
    },
    "/model-management/manage-default-models": {
      "filePath": "model-management.manage-default-models.tsx"
    },
    "/model-management/": {
      "filePath": "model-management.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
