/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TranslateImport } from './routes/translate'
import { Route as ManageProvidersImport } from './routes/manage-providers'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TranslateRoute = TranslateImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRoute,
} as any)

const ManageProvidersRoute = ManageProvidersImport.update({
  id: '/manage-providers',
  path: '/manage-providers',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/manage-providers': {
      id: '/manage-providers'
      path: '/manage-providers'
      fullPath: '/manage-providers'
      preLoaderRoute: typeof ManageProvidersImport
      parentRoute: typeof rootRoute
    }
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage-providers': typeof ManageProvidersRoute
  '/translate': typeof TranslateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manage-providers': typeof ManageProvidersRoute
  '/translate': typeof TranslateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/manage-providers': typeof ManageProvidersRoute
  '/translate': typeof TranslateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manage-providers' | '/translate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manage-providers' | '/translate'
  id: '__root__' | '/' | '/manage-providers' | '/translate'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageProvidersRoute: typeof ManageProvidersRoute
  TranslateRoute: typeof TranslateRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageProvidersRoute: ManageProvidersRoute,
  TranslateRoute: TranslateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/manage-providers",
        "/translate"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/manage-providers": {
      "filePath": "manage-providers.tsx"
    },
    "/translate": {
      "filePath": "translate.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
